language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Prerequisites
  - ./download_other_githubs
  - sudo apt-get install tidy

services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 CodeToHtmlConsoleTest.pro
  - make debug --silent
  - ./CodeToHtmlConsoleTest
  # Console
  - qmake -qt=qt5 CodeToHtmlConsole.pro
  - make debug --silent
  - ./CodeToHtmlConsole --about
  # Desktop
  - qmake -qt=qt5 CodeToHtmlDesktop.pro
  - make debug --silent
  - ./CodeToHtmlDesktop &
  - sleep 10
  - sudo killall CodeToHtmlDesktop
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint

after_success: 
  - bash <(curl -s https://codecov.io/bash)
